version: '3'
services:
    fauxton:
      image: 3apaxicom/fauxton
      ports:
        - 6945:8000
      depends_on:
        - couchdb
      command:
        - sh
        - "-c"
        - "fauxton -c http://couchdb:5984"
    couchdb:
      image: couchdb
      container_name: couchdb
      env_file: .env
      ports:
        - '5984:5984'
      volumes:
        - db_data:/opt/couchdb/data
      networks:
        - "public"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.notorious-backend.rule=Host(`${COUCH_SUBDOMAIN}.${DOMAIN_NAME}`)"
        - "traefik.http.routers.notorious-backend.entrypoints=https"
        - "traefik.http.routers.notorious-backend.tls.certresolver=myhttpchallenge"
        - "traefik.http.services.notorious-backend.loadbalancer.server.port=5984"
    notorious_web:
      container_name: notorious
      build:
        context: .
        dockerfile: Dockerfile.prod
      ports:
        - '9645:80'
      networks:
        - public
      env_file: .env
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.notorious.rule=Host(`${NOTORIOUS_SUBDOMAIN}.${DOMAIN_NAME}`)"
        - "traefik.http.routers.notorious.entrypoints=https"
        - "traefik.http.routers.notorious.tls.certresolver=myhttpchallenge"
        - "traefik.http.services.notorious-web.loadbalancer.server.port=9645"

volumes:
  db_data:
    driver: local
networks:
  public:
    external: true
