version: '3'
services:
    fauxton:
      image: 3apaxicom/fauxton
      ports:
        - 6945:8000
      depends_on:
        - couchdb
      command:
        - sh
        - "-c"
        - "fauxton -c http://couchdb:5984"
    couchdb:
      image: couchdb
      container_name: couchdb
      env_file: .env
      ports:
        - '5984:5984'
      volumes:
        - db_data:/opt/couchdb/data
      networks:
        - "public"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.fastnote-backend.rule=Host(`couch.example.com`)"
        - "traefik.http.routers.fastnote-backend.entrypoints=https"
        - "traefik.http.routers.fastnote-backend.tls.certresolver=myhttpchallenge"
        - "traefik.http.services.noteapp_couchdb.passHostHeader=true"
    fastnote_web:
      container_name: fastnote
      build:
        context: .
        dockerfile: Dockerfile.prod
      ports:
        - '9645:80'
      networks:
        - public
      env_file: .env
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.fastnote.rule=Host(`notorious.example.com`)"
        - "traefik.http.routers.fastnote.entrypoints=https,http"
        - "traefik.http.routers.fastnote.tls.certresolver=myhttpchallenge"

volumes:
  db_data:
    driver: local
networks:
  public:
    external: true
